"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getProduct } from "@/lib/api/products";
import { getLocalProduct } from "@/lib/product-storage";
import { Product } from "@/lib/types";
import { formatCategory, formatPrice } from "@/lib/utils";
import Loader from "../ui/Loader";
import ErrorState from "../ui/ErrorState";
export default function ProductDetailClient({ id }: { id: number }) { const [product, setProduct] = useState<Product | null>(null); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false); const [error, setError] = useState(""); useEffect(() => { (async () => { try { const local = getLocalProduct(id); if (local?.title) setProduct(local); else setProduct(await getProduct(id)); } catch (err: any) { if (err?.status === 404 || err?.message?.toLowerCase().includes("not found")) setNotFound(true); else setError(err?.message || "Unable to load product."); } finally { setLoading(false); } })(); }, [id]); if (loading) return <Loader />; if (notFound) return <ErrorState message={`Product ${id} was not found.`} onRetry={() => window.location.reload()} />; if (error || !product) return <ErrorState message={error || "Product could not be loaded."} onRetry={() => window.location.reload()} />; return <div className="space-y-6"><div className="flex items-center justify-between"><Link href="/products" className="text-sm text-blue-600">← Back to Products</Link><Link href={`/products/${product.id}/edit`} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Edit Product</Link></div><div className="rounded-xl border bg-white p-6 shadow-sm"><div className="grid gap-8 lg:grid-cols-2"><div><img src={product.thumbnail} alt={product.title} className="h-[400px] w-full rounded-xl bg-gray-50 object-contain" /></div><div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-600">{formatCategory(product.category)}</span><h1 className="mt-4 text-3xl font-bold">{product.title}</h1><p className="mt-4 leading-7 text-gray-600">{product.description}</p><div className="mt-6 grid grid-cols-2 gap-4">{[["Price", formatPrice(product.price)], ["Rating", product.rating.toFixed(1)], ["Stock", String(product.stock)], ["Product ID", `#${product.id}`]].map(([label, value]) => <div key={label} className="rounded-lg bg-gray-50 p-4"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div></div></div></div>{product.reviews?.length ? <div className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Reviews</h2><div className="mt-5 divide-y">{product.reviews.map((review, index) => <div key={`${review.reviewerEmail}-${index}`} className="py-5"><p className="font-semibold">{review.reviewerName}</p><p className="text-xs text-gray-500">{review.reviewerEmail}</p><p className="mt-3 text-sm text-gray-600">{review.comment}</p></div>)}</div></div> : null}</div>; }
