"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { addProduct, deleteProduct, getCategories, getProducts, getProductsByCategory, searchProducts } from "@/lib/api/products";
import { applyLocalOverrides, isLocalOnlyProduct, saveDeletedProduct } from "@/lib/product-storage";
import { Category, Product } from "@/lib/types";
import { clampPage, parsePageSize, parsePositiveInt } from "@/lib/utils";
import ProductCard from "./ProductCard";
import ProductTable from "./ProductTable";
import ProductFilters from "./ProductFilters";
import Pagination from "./Pagination";
import Loader from "../ui/Loader";
import ErrorState from "../ui/ErrorState";
import Button from "../ui/Button";
import Modal from "../ui/Modal";
export default function ProductsClient() { const params = useSearchParams(); const pageSize = parsePageSize(params.get("size")); const search = params.get("search")?.trim() ?? ""; const category = params.get("category") ?? ""; const sort = params.get("sort") as "price" | "rating" | "title" | null; const order: "asc" | "desc" = params.get("order") === "desc" ? "desc" : "asc"; const [products, setProducts] = useState<Product[]>([]); const [total, setTotal] = useState(0); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const requestId = useRef(0); const controller = useRef<AbortController | null>(null);
 const [deleteTarget, setDeleteTarget] = useState<Product | null>(null); const [deleting, setDeleting] = useState(false);
 const safeTotalPages = Math.max(1, Math.ceil(total / pageSize));
 const page = clampPage(params.get("page"), 1, safeTotalPages);
 useEffect(() => { getCategories().then(setCategories).catch(() => undefined); }, []);
 useEffect(() => { const requestedPage = parsePositiveInt(params.get("page"), 1); if (requestedPage !== page) { const nextParams = new URLSearchParams(params.toString()); nextParams.set("page", String(page)); window.history.replaceState(null, "", `${window.location.pathname}?${nextParams.toString()}`); } }, [params, page]);
 useEffect(() => { let active = true; async function load() { const current = ++requestId.current; controller.current?.abort(); const nextController = new AbortController(); controller.current = nextController; setLoading(true); setError(""); try { const delay = Number(process.env.NEXT_PUBLIC_API_DELAY || 0); let response; if (search && category) { response = await searchProducts(search, { limit: 0, delay }); if (!active || current !== requestId.current) return; let filtered = applyLocalOverrides(response.products).filter(product => product.category === category); if (sort) filtered.sort((a, b) => { const result = sort === "title" ? a.title.localeCompare(b.title) : sort === "price" ? a.price - b.price : a.rating - b.rating; return order === "asc" ? result : -result; }); const start = (page - 1) * pageSize; setProducts(filtered.slice(start, start + pageSize)); setTotal(filtered.length); return; } const requestParams = { limit: pageSize, skip: (page - 1) * pageSize, sortBy: sort || undefined, order: sort ? order : undefined, delay }; response = search ? await searchProducts(search, requestParams) : category ? await getProductsByCategory(category, requestParams) : await getProducts(requestParams); if (!active || current !== requestId.current) return; const localProducts = applyLocalOverrides(response.products); setProducts(localProducts.slice(0, pageSize)); setTotal(Math.max(0, response.total + applyLocalOverrides([]).length - (response.products.length - localProducts.length))); } catch (err: any) { if (err?.code === "ERR_CANCELED") return; if (active && current === requestId.current) setError(err?.message || "Unable to load products."); } finally { if (active && current === requestId.current) setLoading(false); } } load(); return () => { active = false; controller.current?.abort(); }; }, [search, category, sort, order, page, pageSize]);
 async function handleDelete() { if (!deleteTarget || deleting) return; setDeleting(true); try { if (isLocalOnlyProduct(deleteTarget.id)) { saveDeletedProduct(deleteTarget.id); setProducts(current => current.filter(item => item.id !== deleteTarget.id)); setTotal(current => Math.max(0, current - 1)); setDeleteTarget(null); return; } await deleteProduct(deleteTarget.id); saveDeletedProduct(deleteTarget.id); setProducts(current => current.filter(item => item.id !== deleteTarget.id)); setTotal(current => Math.max(0, current - 1)); setDeleteTarget(null); } catch (err: any) { setError(err?.message || "Unable to delete product."); } finally { setDeleting(false); } }
 return <><div className="space-y-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="text-2xl font-bold">Products</h1><p className="mt-1 text-sm text-gray-500">Manage your product catalog.</p></div><Link href="/products/new" className="rounded-lg bg-blue-600 px-4 py-2.5 text-center text-sm font-medium text-white">+ Add Product</Link></div><ProductFilters categories={categories} />{loading && <Loader />}{!loading && error && <ErrorState message={error} onRetry={() => window.location.reload()} />}{!loading && !error && products.length === 0 && <div className="rounded-xl border bg-white p-12 text-center"><h3 className="font-semibold">No products found</h3><p className="mt-1 text-sm text-gray-500">Try changing your search or filters.</p></div>}{!loading && !error && products.length > 0 && <><ProductTable products={products} onDelete={setDeleteTarget} /><div className="space-y-3">{products.map(product => <ProductCard key={product.id} product={product} onDelete={setDeleteTarget} />)}</div><Pagination page={page} pageSize={pageSize} total={total} /></>}</div><Modal open={Boolean(deleteTarget)} title="Delete product?" onClose={() => setDeleteTarget(null)}><p className="text-sm text-gray-600">Are you sure you want to delete {deleteTarget?.title}?</p><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" disabled={deleting} onClick={() => setDeleteTarget(null)}>Cancel</Button><Button type="button" variant="danger" disabled={deleting} onClick={handleDelete}>{deleting ? "Deleting..." : "Delete"}</Button></div></Modal></>; }
